name: Generate Datas

# Cartões de resumo
      - usa : ações/checkout@v2
      - usa : vn7n24fzkq/github-profile-summary-cards@release
        ambiente :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        com :
          NOME DE USUÁRIO : ${{ github.repository_owner }}

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: luhferreira
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
